// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: proto/game_stats.proto

package lila_assgnm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaCode int32 `protobuf:"varint,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
}

func (x *GameStatsRequest) Reset() {
	*x = GameStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatsRequest) ProtoMessage() {}

func (x *GameStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatsRequest.ProtoReflect.Descriptor instead.
func (*GameStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GameStatsRequest) GetAreaCode() int32 {
	if x != nil {
		return x.AreaCode
	}
	return 0
}

type GameStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaCode  int32       `protobuf:"varint,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	GameModes []*GameMode `protobuf:"bytes,2,rep,name=game_modes,json=gameModes,proto3" json:"game_modes,omitempty"`
}

func (x *GameStatsResponse) Reset() {
	*x = GameStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatsResponse) ProtoMessage() {}

func (x *GameStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatsResponse.ProtoReflect.Descriptor instead.
func (*GameStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GameStatsResponse) GetAreaCode() int32 {
	if x != nil {
		return x.AreaCode
	}
	return 0
}

func (x *GameStatsResponse) GetGameModes() []*GameMode {
	if x != nil {
		return x.GameModes
	}
	return nil
}

type GameMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode    string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Players int32  `protobuf:"varint,2,opt,name=players,proto3" json:"players,omitempty"`
}

func (x *GameMode) Reset() {
	*x = GameMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMode) ProtoMessage() {}

func (x *GameMode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMode.ProtoReflect.Descriptor instead.
func (*GameMode) Descriptor() ([]byte, []int) {
	return file_proto_game_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GameMode) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GameMode) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

var File_proto_game_stats_proto protoreflect.FileDescriptor

var file_proto_game_stats_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x22, 0x2f, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x64, 0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x65,
	0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x72,
	0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52,
	0x09, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x32, 0x58, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x20,
	0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x76, 0x79,
	0x75, 0x6b, 0x74, 0x68, 0x2f, 0x6c, 0x69, 0x6c, 0x61, 0x2d, 0x61, 0x73, 0x73, 0x67, 0x6e, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_stats_proto_rawDescOnce sync.Once
	file_proto_game_stats_proto_rawDescData = file_proto_game_stats_proto_rawDesc
)

func file_proto_game_stats_proto_rawDescGZIP() []byte {
	file_proto_game_stats_proto_rawDescOnce.Do(func() {
		file_proto_game_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_stats_proto_rawDescData)
	})
	return file_proto_game_stats_proto_rawDescData
}

var file_proto_game_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_game_stats_proto_goTypes = []interface{}{
	(*GameStatsRequest)(nil),  // 0: gamestats.GameStatsRequest
	(*GameStatsResponse)(nil), // 1: gamestats.GameStatsResponse
	(*GameMode)(nil),          // 2: gamestats.GameMode
}
var file_proto_game_stats_proto_depIdxs = []int32{
	2, // 0: gamestats.GameStatsResponse.game_modes:type_name -> gamestats.GameMode
	0, // 1: gamestats.GameStats.GetGameStats:input_type -> gamestats.GameStatsRequest
	1, // 2: gamestats.GameStats.GetGameStats:output_type -> gamestats.GameStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_game_stats_proto_init() }
func file_proto_game_stats_proto_init() {
	if File_proto_game_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_stats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_stats_proto_goTypes,
		DependencyIndexes: file_proto_game_stats_proto_depIdxs,
		MessageInfos:      file_proto_game_stats_proto_msgTypes,
	}.Build()
	File_proto_game_stats_proto = out.File
	file_proto_game_stats_proto_rawDesc = nil
	file_proto_game_stats_proto_goTypes = nil
	file_proto_game_stats_proto_depIdxs = nil
}
